name: Build NMS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Build
      run: dotnet publish -c Release Selly/Selly.NMS.Web/
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Image
      run: docker build -t ghcr.io/alex-stevens/selly:v1 Selly/Selly.NMS.Web/
    - name: Push Image
      run: docker push ghcr.io/alex-stevens/selly:v1
